# Generated by Django 3.2.16 on 2023-05-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0003_auto_20230509_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kategori_produk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produk.kategoriproduk'),
        ),
    ]
