# Generated by Django 3.2.16 on 2023-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('email_pelanggan', models.EmailField(max_length=254)),
                ('password_pelanggan', models.CharField(max_length=100)),
                ('alamat_pelanggan', models.TextField()),
                ('nomor_telepon_pelanggan', models.CharField(max_length=20)),
            ],
        ),
    ]
