# Generated by Django 3.2.16 on 2023-05-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0004_produk_kategori_produk'),
        ('Pengiriman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengiriman',
            old_name='nama_pengiriman',
            new_name='nama_pelanggan',
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='alamat_pengiriman',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='nomor_telepon_pelanggan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='produk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produk.produk'),
        ),
    ]
