# Generated by Django 3.2.16 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pengiriman', '0002_auto_20230510_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengiriman',
            name='kode_pos',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='kota',
            field=models.CharField(default='default_kota_value', max_length=50),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='provinsi',
            field=models.CharField(default='Provinsi', max_length=50),
        ),
    ]
